theme:
  name: material
  palette:
    primary: custom
site_name: Research Data Management
nav:
  - Home: index.md
  - Download:
      - Introduction: download/introduction.md
      - Generate personal access token: download/create_pat.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
