theme:
  name: material
  palette:
    primary: custom
  features:
    - content.code.copy
site_name: Research Data Management
nav:
  - Home: index.md
  - Batch:
      - Introduction: batch/batch_introduction.md
      - Register: batch/batch_registration.md
      - Edit: batch/batch_edit.md
  - Download:
      - Introduction: download/download_introduction.md
      - Personal access token: download/download_create_pat.md
      - Execute download: download/download_run_download.md
  - Experiment:
      - Introduction: experiment/experiment_introduction.md
      - Creation: experiment/experiment_creation.md
  - Measurement:
      - Introduction: measurement/measurement_introduction.md
      - Registration: measurement/measurement_registration.md
      - Editing: measurement/measurement_edit.md
      - Upload: measurement/measurement_upload_data.md
  - Ontology:
      - Introduction: ontology_search/ontology_search_introduction.md
  - Project:
      - Introduction: project/project_introduction.md
      - Registration: project/project_registration.md
      - Editing: project/project_edit.md
      - Access Management: project/project_access.md
  - User:
      - User Registration: user/user_registration.md
      - Password Reset: user/password_reset.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
